'use client';

import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';

export default function PrivacyPage() {
  const router = useRouter();

  return (
    <div className="min-h-screen bg-gradient-to-br from-primary-500 via-secondary-500 to-accent-500">
      <div className="max-w-4xl mx-auto px-4 py-8">
        <div className="mb-8">
          <Button
            onClick={() => router.back()}
            variant="ghost"
            className="text-white hover:bg-white/10"
          >
            ← Back
          </Button>
        </div>

        <Card variant="default" className="mb-8">
          <div className="text-center mb-8">
            <h1 className="text-4xl font-bold text-white mb-2">Privacy Policy</h1>
            <p className="text-white/80">Last updated: January 2025</p>
          </div>

          <div className="space-y-8 text-white/90">
            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">🏃 About Athlete IQ</h2>
              <p className="mb-4">
                Athlete IQ is a fitness analytics platform that connects to your Strava account to provide 
                AI-powered insights about your training, performance, and fitness trends. We help athletes 
                understand their data through intelligent analysis and personalized recommendations.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">📊 What Data We Collect</h2>
              <div className="space-y-3">
                <div>
                  <h3 className="text-lg font-medium text-white mb-2">From Strava:</h3>
                  <ul className="list-disc list-inside space-y-1 ml-4">
                    <li>Your public profile information (name, profile photo)</li>
                    <li>Activity data (rides, runs, swims, etc.)</li>
                    <li>Performance metrics (distance, duration, elevation, power, heart rate)</li>
                    <li>GPS routes and maps for activities</li>
                    <li>Activity titles, descriptions, and types</li>
                    <li>Segment efforts and achievements</li>
                  </ul>
                </div>
                <div>
                  <h3 className="text-lg font-medium text-white mb-2">Generated by Our App:</h3>
                  <ul className="list-disc list-inside space-y-1 ml-4">
                    <li>Training Stress Score (TSS) calculations</li>
                    <li>Fitness metrics (CTL, ATL, TSB)</li>
                    <li>AI-generated activity summaries and insights</li>
                    <li>Chat conversation history with our AI assistant</li>
                    <li>Custom analysis and performance trends</li>
                  </ul>
                </div>
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">🔒 How We Use Your Data</h2>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li><strong>Fitness Analysis:</strong> Calculate training metrics and provide performance insights</li>
                <li><strong>AI Conversations:</strong> Enable contextual chat about your activities and training</li>
                <li><strong>Personalization:</strong> Tailor recommendations based on your activity patterns</li>
                <li><strong>Data Visualization:</strong> Create charts and graphs of your fitness progress</li>
                <li><strong>Search & Discovery:</strong> Help you find and analyze specific activities</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">🛡️ Data Storage & Security</h2>
              <div className="space-y-3">
                <p>
                  <strong>Where:</strong> Your data is stored in secure cloud infrastructure using industry-standard 
                  encryption both in transit and at rest.
                </p>
                <p>
                  <strong>Backend Storage:</strong> Activity data and AI-generated insights are stored in our 
                  PostgreSQL database and Pinecone vector database for semantic search capabilities.
                </p>
                <p>
                  <strong>Authentication:</strong> We use OAuth 2.0 through Strava, meaning we never store your 
                  Strava password. Access tokens are securely managed and refreshed automatically.
                </p>
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">🚫 What We Don't Do</h2>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>We <strong>never</strong> sell your personal data to third parties</li>
                <li>We <strong>don't</strong> share your activity data with other users</li>
                <li>We <strong>don't</strong> use your data for advertising purposes</li>
                <li>We <strong>don't</strong> modify or post to your Strava account</li>
                <li>We <strong>don't</strong> access private/hidden activities unless you sync them</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">🤝 Third-Party Services</h2>
              <div className="space-y-3">
                <p>
                  <strong>Strava:</strong> We integrate with Strava's API to access your fitness data. 
                  Your use of Strava is subject to their privacy policy.
                </p>
                <p>
                  <strong>OpenAI:</strong> We use OpenAI's GPT-4 to power our AI assistant. Your activity 
                  data is processed by OpenAI to generate insights, but is not used to train their models.
                </p>
                <p>
                  <strong>AWS:</strong> Our infrastructure runs on Amazon Web Services, which provides 
                  enterprise-grade security and compliance.
                </p>
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">🎯 Your Rights & Controls</h2>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li><strong>Access:</strong> View all your synced data through the dashboard</li>
                <li><strong>Export:</strong> Download your data at any time (coming soon)</li>
                <li><strong>Delete:</strong> Remove your account and all associated data</li>
                <li><strong>Disconnect:</strong> Revoke Strava access at any time through Strava's settings</li>
                <li><strong>Sync Control:</strong> Choose how many days of activities to sync (1-1095 days)</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">🍪 Cookies & Local Storage</h2>
              <p>
                We use essential cookies and local storage for:
              </p>
              <ul className="list-disc list-inside space-y-1 ml-4 mt-2">
                <li>Maintaining your login session</li>
                <li>Storing your chat conversation context</li>
                <li>Remembering your UI preferences</li>
              </ul>
              <p className="mt-2">
                We do not use tracking cookies or analytics that could identify you personally.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">📧 Contact Us</h2>
              <p>
                If you have questions about this privacy policy or how we handle your data, please contact us at:
              </p>
              <p className="mt-2">
                <strong>Email:</strong> privacy@athlete-iq.com<br />
                <strong>GitHub:</strong> github.com/athlete-iq/issues
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">🔄 Changes to This Policy</h2>
              <p>
                We may update this privacy policy from time to time. We will notify you of any significant 
                changes by posting a notice in the app or sending you an email. Your continued use of 
                Athlete IQ after changes constitutes acceptance of the updated policy.
              </p>
            </section>
          </div>

          <div className="mt-12 pt-8 border-t border-white/20 text-center">
            <p className="text-white/60 text-sm">
              By using Athlete IQ, you agree to this Privacy Policy and our Terms of Service.
            </p>
          </div>
        </Card>

        <div className="text-center mb-8">
          <Button
            onClick={() => router.push('/login')}
            variant="secondary"
            size="lg"
          >
            Back to Login
          </Button>
        </div>
      </div>
    </div>
  );
}